### ISSUE TITLE
Nuevas listas

### ISSUE THREAD

**Issue by nanomvortex** [JamepDev/ArchivosLudicos#8]
Solo se me ocurren dos (o tres si expandes el "scope" del proyecto)
- Tiendas de videojuegos, con sus ventajas y advertencias
- Desarrolladores indie
- Motores de juego?

Ah, otra cosa, no tengo idea cómo funciona Hugo pero la intuición me dice que simplemente es cosa de añadir los artículos en Markdown a los docs y el software hace el resto.

**Comment by JamepDev** [comment]
Buenas ideas, estaría bueno para expandir el proyecto 

Sobre Hugo, es básicamente es lo que dijiste, solo que para modificar el menú tienes que modificar este archivo https://github.com/JamepDev/ArchivosLudicos/blob/main/content/menu/index.md

**Comment by nanomvortex** [comment]
Super, haré mi PR ahora mismo.
Dejo esto abierto por si proponen más listas, supongo (?)
O cierra el issue si quieres, je.
